services:
  apigateway:
    container_name: apigateway
    image: nginx:alpine
    build: ms_apigateway/.
    ports:
      - 8000:80

  especialidad:
    container_name: especialidad
    image: especialidad
    build: ms_especialidad/.
    env_file:
      - .env

  seguridad:
    container_name: seguridad
    image: seguridad
    build: ms_seguridad/.
    env_file:
      - .env