services:
  apigateway:
    container_name: apigateway
    image: nginx:alpine
    build: apigateway/.
    ports:
      - 8000:80

  ficheros:
    container_name: ficheros
    image: ficheros
    build: ficheros/.
    env_file:
      - .env

  usuarios:
    container_name: usuarios
    image: usuarios
    build: usuarios/.
    env_file:
      - .env
    depends_on:
      - ficheros
  
  medicos:
    container_name: medicos
    image: medicos
    build: medicos/.
    env_file:
      - .env
    depends_on:
      - ficheros

  productos:
      container_name: productos
      image: productos
      build: productos/.
      env_file:
        - .env