from sqlalchemy import Column, Integer, String, Table, ForeignKey, DATE, Numeric, TIMESTAMP, CHAR, BOOLEAN
from .db import Base, engine

class TipoDoc(Base):
    __table__ = Table("tipo_doc", Base.metadata,autoload_with=engine,extend_existing=True)

class Especialidad(Base):
    __table__ = Table("especialidad", Base.metadata,autoload_with=engine,extend_existing=True)

class Orden(Base):
    __tablename__ = "ordencompra_logistica"
    oc_id = Column(Integer, primary_key=True)
    oc_tipoorden = Column(String(10), nullable=False)
    oc_fecoc = Column(DATE, nullable=False, server_default="now()")
    oc_invent = Column(Integer, nullable=False, server_default="1")
    oc_ppresup = Column(String(20))
    oc_ccosto = Column(String(60))
    oc_presup = Column(Integer)
    oc_personaid = Column(Integer, nullable=False)
    oc_vendedor = Column(String(100))
    oc_vendtel = Column(String(100))
    oc_vendmail = Column(String(100))
    oc_monedaid = Column(Integer, nullable=False)
    oc_tcaoc = Column(Numeric(18, 3), server_default="0")
    oc_mediopagoid = Column(Integer)
    oc_formapago = Column(String(30))
    oc_estoc = Column(String(25), nullable=False)
    oc_equipo = Column(String(25), nullable=False)
    oc_usuoc = Column(String(25), nullable=False)
    oc_fecpro = Column(TIMESTAMP, nullable=False, server_default="now()")
    oc_fecmod = Column(TIMESTAMP)
    oc_usumod = Column(String(25))
    oc_banco = Column(CHAR(3))
    oc_tipocuenta = Column(String(15))
    oc_nrocuenta = Column(String(30))
    oc_cci = Column(String(30))
    oc_monbanco = Column(Integer)
    oc_ref = Column(String(250))
    oc_obs = Column(String(250))
    oc_autoriza = Column(String(25))
    oc_cargo = Column(String(3))
    oc_descg = Column(Numeric(18, 2), server_default="0")
    oc_remitente = Column(String(25))
    oc_autoriza2 = Column(String(25))
    oc_cargo2 = Column(String(3))
    usuario_conformidad = Column(String(25))
    conformidad = Column(TIMESTAMP)
    oc_autorizacion1 = Column(TIMESTAMP)
    oc_autorizacion2 = Column(TIMESTAMP)
    solicita_aut = Column(BOOLEAN, server_default="false")
    obs_autoriza1 = Column(String(250))
    obs_autoriza2 = Column(String(250))
    oc_obs2 = Column(String(250))